from little_a2s.events import ClientEventRules
from little_a2s.reader import Reader
from little_a2s.rules.arma3 import Arma3DLC, Arma3Difficulty, Arma3Mod, Arma3Rules
from tests.constants import A2S_RULES_ARMA3


def test_parse_arma3_rules() -> None:
    event = ClientEventRules.from_reader(Reader(A2S_RULES_ARMA3[5:]))
    rules = Arma3Rules.from_rules(event)
    assert rules == Arma3Rules(
        version=3,
        overflow=8,
        dlc=Arma3DLC(7167),
        difficulty=Arma3Difficulty(
            difficulty=3,
            skill=3,
            advanced_flight_model=False,
            third_person_view=True,
            weapon_crosshair=False,
        ),
        dlc_hashes=[
            4130562402,
            336502661,
            1640185470,
            997605112,
            308207932,
            2134069525,
            276692972,
            2866195189,
            1364250724,
            1847722774,
            3022557231,
            1171172752,
        ],
        mods=[
            Arma3Mod(hash=3601378554, dlc=True, steam_id=1681170, name=""),
            Arma3Mod(hash=4128132406, dlc=True, steam_id=2647760, name=""),
            Arma3Mod(hash=619248735, dlc=True, steam_id=2647830, name=""),
            Arma3Mod(
                hash=97296156,
                dlc=False,
                steam_id=2794721649,
                name="Advanced Vault System",
            ),
            Arma3Mod(
                hash=878463927,
                dlc=False,
                steam_id=2198339170,
                name="Alternative Running",
            ),
            Arma3Mod(
                hash=3304015857,
                dlc=False,
                steam_id=2060770170,
                name="@Arsenal Search",
            ),
            Arma3Mod(
                hash=593938911,
                dlc=False,
                steam_id=3085697583,
                name="Automatic Warning Suppressor",
            ),
            Arma3Mod(
                hash=2838544570,
                dlc=False,
                steam_id=2791403093,
                name="Better Inventory",
            ),
            Arma3Mod(
                hash=3951760669,
                dlc=False,
                steam_id=2079283616,
                name="@Blurry Laser",
            ),
            Arma3Mod(
                hash=560497832,
                dlc=False,
                steam_id=450814997,
                name="Community Base Addons v3.18.4",
            ),
            Arma3Mod(
                hash=1630190913,
                dlc=False,
                steam_id=837729515,
                name="@CH View Distance",
            ),
            Arma3Mod(
                hash=3931178414,
                dlc=False,
                steam_id=2993442344,
                name="Dying and Hit Reactions",
            ),
            Arma3Mod(
                hash=3207441395,
                dlc=False,
                steam_id=3435581126,
                name="@Drongos Grenade Tweaks",
            ),
            Arma3Mod(
                hash=3826176653,
                dlc=False,
                steam_id=3056632823,
                name="E22: Northstar",
            ),
            Arma3Mod(
                hash=815866796,
                dlc=False,
                steam_id=2815603726,
                name="E22: Russian Armed Forces",
            ),
            Arma3Mod(
                hash=3241463635,
                dlc=False,
                steam_id=686802825,
                name="Eden Objects",
            ),
            Arma3Mod(
                hash=298189707,
                dlc=False,
                steam_id=3489262669,
                name="Expanded Actions and Vehicle Animations",
            ),
            Arma3Mod(
                hash=3488009742,
                dlc=False,
                steam_id=3346427969,
                name="Hide Among The Grass",
            ),
            Arma3Mod(
                hash=3696902342,
                dlc=False,
                steam_id=3333302397,
                name="JCA - Infantry Arsenal",
            ),
            Arma3Mod(
                hash=2426246259,
                dlc=False,
                steam_id=3473383676,
                name="JCA - Infantry Equipment",
            ),
            Arma3Mod(
                hash=509305708,
                dlc=False,
                steam_id=3032405142,
                name="JCA - QOL Essentials V2",
            ),
            Arma3Mod(
                hash=689280488,
                dlc=False,
                steam_id=2928582359,
                name="JCA - SPAR Retexture Project",
            ),
            Arma3Mod(
                hash=2914706250,
                dlc=False,
                steam_id=3407970596,
                name="JSRS Soundmod 2025 Beta - AiO Compat Files",
            ),
            Arma3Mod(
                hash=1730530565,
                dlc=False,
                steam_id=3407948300,
                name="JSRS Soundmod 2025 Beta RC3 - Beta",
            ),
            Arma3Mod(
                hash=3762815891,
                dlc=False,
                steam_id=2969350304,
                name="@Ladder Tweak Remastered",
            ),
            Arma3Mod(
                hash=215264130,
                dlc=False,
                steam_id=1770265310,
                name="No More Aircraft Bouncing",
            ),
            Arma3Mod(
                hash=1666079342,
                dlc=False,
                steam_id=2806487814,
                name="WebKnights Footsteps",
            ),
            Arma3Mod(
                hash=4094218871,
                dlc=False,
                steam_id=2129532219,
                name="SFX Project: Remastered",
            ),
            Arma3Mod(
                hash=2078761846,
                dlc=False,
                steam_id=1867660876,
                name="Pylon Manager V4",
            ),
            Arma3Mod(
                hash=2193669517,
                dlc=False,
                steam_id=3450227250,
                name="@Reload While Aiming",
            ),
            Arma3Mod(
                hash=2995945959,
                dlc=False,
                steam_id=708931058,
                name="@SSD Death Screams 21",
            ),
            Arma3Mod(
                hash=4198938498,
                dlc=False,
                steam_id=3584152650,
                name="UH-80 Ghost Hawk Plus",
            ),
            Arma3Mod(
                hash=2092903220,
                dlc=False,
                steam_id=2161671937,
                name="Vehicle Inventory System",
            ),
            Arma3Mod(
                hash=1005339336,
                dlc=False,
                steam_id=3132949782,
                name="WBK Simple Blood",
            ),
            Arma3Mod(
                hash=725198233,
                dlc=False,
                steam_id=1793762277,
                name="White Phosphor - No ACE",
            ),
        ],
        signatures=[
            "16aa-3lsr-2020-01-01.7af9",
            "2600K",
            "3den_Objects",
            "a3",
            "A3RO_1.1",
            "A3TI",
            "A3TI_REAPIR",
            "AdvancedRappelling",
            "AdvancedTowing",
            "AdvancedUrbanRappelling",
            "AGE",
            "AlkSwimFaster",
            "ALP",
            "ANZ",
            "ASBE_1.1.1",
            "Automatic-Warning-Suppressor",
            "badbenson",
            "better_Inventory",
            "BloodwynBWLH",
            "Bromine",
            "Casper_TFG",
            "cba_3.18.4.250711",
            "CCA_1.0.1.0-11cad8fc",
            "CH",
            "Cryptid",
            "csla",
            "cup_terrains_core-1.17.1",
            "cup_units-1.18.1",
            "cup_vehicles-1.18.1",
            "cup_weapons-1.18.1",
            "CZB",
            "dbag",
            "Detected_error",
            "dirt_0.4.0.0",
            "DITC_2025",
            "diwako_dui_1.12.2.0",
            "drakovac_154",
            "drongosgrenadetweaks",
            "DVK_ALTCSAT",
            "dyel",
            "DrunkeN",
            "ef",
            "EnhancedGPS",
            "EnhancedMap",
            "EnhancedSoundscape_2020_01_05",
            "enh_8.7.1",
            "EricJAddons",
            "Escalation2022",
            "f35_hnt",
            "Fat_Lurch_TurretEnhanced",
            "Fat_Lurch_VIS",
            "Fat_Lurch_White_Phosphor_No_ACE",
            "FA_EMB312",
            "fhs",
            "FVL",
            "GAC",
            "GanX",
            "GENIX",
            "GF_ReColor",
            "globe",
            "gm",
            "GX_DRONES",
            "hatchet_interaction_0.3.1",
            "ibr_regero11",
            "ibr_yul11",
            "icm",
            "iskyefx",
            "iskyStocatto",
            "ISKY_EFX",
            "JAMReconHoods",
            "Jason",
            "JFXAMv2",
            "JointCom_Armoury",
            "JointCom_Armoury",
            "JSDFmod",
            "jsrs_2025_aio_comapt",
            "jsrs_2025_main",
            "jsrs_extra_2020",
            "jsrs_soundmod_2020_v2",
            "juju",
            "Kaska",
            "KJW_TwoPrimaryWeapons",
            "LalaPeralv01",
            "lambs_2.6.1.502",
            "lambs_2.6.2.1",
            "lambs_mod",
            "larisa",
            "Leopard20.ADT",
            "lot_aaf_scar",
            "lxrf_cba_compat",
            "lxws_cba_compat",
            "magRepack",
            "Maxjoiner",
            "Max_Women",
            "MBG_AGB",
            "mehland_v120",
            "MHS",
            "Modern_Pistol_Pack",
            "Modules_f_JoeLiScripts",
            "MSS",
            "MTK_Mods",
            "Nemo_VOEREX4",
            "NIArms",
            "NightFury",
            "NoMoreAircraftBouncing",
            "pdb",
            "pdt_envg",
            "PeralAH1Zv01",
            "PeralF16v01",
            "POLPOX",
            "POLPOX_LadderTweakRemastered",
            "POLPOX_MapToolsRemastered",
            "qav",
            "r0dx864",
            "rf",
            "RKSLStudios2019",
            "Ruf",
            "Ruizu",
            "RUOP_V110",
            "ruPal_mpkey",
            "secondary_gl_1.1.0",
            "SecondWind",
            "SFX_R_Project",
            "sil_hatg",
            "Simcardo",
            "SMA2.7.1",
            "SNMods",
            "SNMods",
            "SNMods",
            "spe",
            "Spearpoint",
            "sps_ai_axmc_v1_4_1",
            "StaticRadios",
            "tacs_2.4.0.55",
            "TCGM_Girls",
            "TCGM_Girls1.55",
            "TCGM_Multi-Girls",
            "TEC",
            "TF47",
            "uh80_tgp_1.0.0.0",
            "UK3CB_BAF_Weapon_3_1",
            "UMB_Colombia_v0.9.5",
            "UnderSiege",
            "Uriki9",
            "USAF_AC130_BETA_V1.2",
            "usaf_fighter-1.0.6.2",
            "usaf_main-1.0.6.2",
            "usaf_utility-1.0.6.2",
            "V12BIKEPACK",
            "vagineer",
            "Variable",
            "vd",
            "vn",
            "VSMAOQ",
            "WarriorsHaven_AlexLyon",
            "WBK_AlternativeRunningv3Keys",
            "WBK_AVS_Key",
            "WBK_BloodMod",
            "WBK_DeathAndHit",
            "WBK_FootstepsKey",
            "WBK_TMW_Key",
            "ws",
            "ww2_spex_2025_07_22",
            "xakuda",
            "zab",
            "Zabb",
            "ZEI-Continued",
            "zen_1.15.1.36",
        ],
    )
