name: Run tests

on:
  push:
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock
  pull_request:
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          python-version: '3.11'
          enable-cache: true
      - run: uv sync --locked --all-extras --dev
      - run: uv run -m pytest
